### ISSUE TITLE
CRUD de Alertas

### ISSUE THREAD

**Issue by BananaaScript** [BananaScripts/Meteorological-Data-Collector#10]
CRUD de Alertas

- Create (Criar Alerta):
O sistema pode definir novos alertas, fornecendo:
Parâmetro (ex: temperatura, pressão)
Limites (mínimo/máximo)
O sistema começa a monitorar esses limites e envia alertas quando são ultrapassados

- Read (Visualizar Alertas):
O sistema pode visualizar uma lista de alertas configurados, com detalhes como:
Parâmetro monitorado
Limites estabelecidos
Histórico de alertas disparados
Ele pode buscar ou filtrar por parâmetro ou status

- Update (Atualizar Alerta):
O sistema pode editar os limites de um alerta existente, ajustando os valores mínimos/máximos e os métodos de notificação

- Delete (Excluir Alerta):
O sistema pode remover um alerta do sistema
O sistema exibe uma confirmação antes de excluir para evitar erros

**Comment by DouglasMedeiros1** [comment]
Fiz o sistema baseado no sistema dos usuarios, porem ainda não testei/ revisei o codigo 

Commit: 0e6c7cd
