### ISSUE TITLE
Modelo Físico do Banco de Dados

### ISSUE THREAD

**Issue by BananaaScript** [BananaScripts/Meteorological-Data-Collector#14]

**Comment by DouglasMedeiros1** [comment]
Fiz nessa semana, porem não há validação da equipe ou do cliente, portanto, não fecharei a tarefa.

Commit: a3a6ea3

**Comment by DouglasMedeiros1** [comment]
Atualizei a imagem do modelo relacional do banco de dados

Commit: 3b9b029

**Comment by DouglasMedeiros1** [comment]
Adicionei o modelo fisico do banco de dados na pasta do backend, na branch development

Commit: ec8ae2c

**Comment by DouglasMedeiros1** [comment]
Atualizei o banco de dados, atualizando ele de forma que siga o novo modelo lógico do banco de dados

Commit (SubModulo Backend): 0ff1ff0

**Comment by DouglasMedeiros1** [comment]
Alterei novamente o banco de dados, e ainda corriji alguns poucos erros no backend para possibilitar a integração

Commit: [f1c58c7](https://github.com/BananaScripts/Meteorological-Data-Collector-Backend/commit/f1c58c7d388b4b7e4767cac533f56750dd791c56)
