### ISSUE TITLE
CRUD dos Parâmetros

### ISSUE THREAD

**Issue by BananaaScript** [BananaScripts/Meteorological-Data-Collector#16]
CRUD de Parâmetros

- Create (Criar Parâmetro):
O administrador pode definir novos parâmetros para uma estação, como:
Tipo de parâmetro (ex: temperatura, umidade)
Unidades de medida

- Read (Visualizar Parâmetros):
 O administrador pode visualizar todos os parâmetros configurados para cada estação, listando:
 Tipo de parâmetro
 Valores atuais monitorados
 Unidades

- Update (Atualizar Parâmetro):
O administrador pode editar parâmetros de uma estação, modificando o tipo de dado monitorado ou as unidades de medida

- Delete (Excluir Parâmetro):
O administrador pode excluir parâmetros que não são mais relevantes para uma estação
O sistema solicita uma confirmação antes de excluir o parâmetro

**Comment by GaSiqueira** [comment]
da2c6c9
