### ISSUE TITLE
Dashboards das Estações

### ISSUE THREAD

**Issue by BananaaScript** [BananaScripts/Meteorological-Data-Collector#22]
Implementar os dados enviados e tratados das estações em dashboards no frontend

Product Backlog ID 22

**Comment by DouglasMedeiros1** [comment]
Adicionei a interface no Frontend, porem não posso implementar nada, já que não há nada pronto para ser implementado

COMMIT: [9cfb901](https://github.com/BananaScripts/Meteorological-Data-Collector-Frontend/commit/9cfb901e2f2399595bceb8535f9e113e7d4fed8d)
