### ISSUE TITLE
Tela de Login e Criação de Conta

### ISSUE THREAD

**Issue by BananaaScript** [BananaScripts/Meteorological-Data-Collector#23]
Desenvolver interface de login para que o usuário possa entrar com sua conta no sistema.

Campos obrigatórios para efetuar o login:
- Email
- Senha

Desenvolver interface para que o usuário possa criar um conta.

Campos Obrigatórios para a criação de conta:
- Nome
- Email
- Senha
- CPF

**Comment by BrunoFerCam** [comment]
Adicionada a tela de login e de cadastro usando um sistema de popup com a estilização completa.

Commit: [35479d7](https://github.com/BananaScripts/Meteorological-Data-Collector-Frontend/commit/35479d7030794038fea18381092855c5e22295ca)
