### ISSUE TITLE
Deploy do banco na web

### ISSUE THREAD

**Issue by BananaaScript** [BananaScripts/Meteorological-Data-Collector#25]
Implementar banco de dados MySQL em algum serviço web

**Comment by DouglasMedeiros1** [comment]
| Subi o banco na web via um site chamado Supabase, relacionado com o Prisma, utilizando postgreesql
| Aguardando confirmação do Cliente, da equipe e do Devops

Commit: [42b52f0](https://github.com/BananaScripts/Meteorological-Data-Collector-Database/commit/42b52f0f8e73f8a5fc65b2a27abf86efefb9283b)

**Comment by DouglasMedeiros1** [comment]
Conectei o Prisma (ORM) ao Supabase. Tambem "Automatizei" o processo de alterar o Database do Deploy.
Documentei tudo no Wiki do Repositorio do Database: [https://github.com/BananaScripts/Meteorological-Data-Collector-Database/wiki/Como-rodar-O-banco](https://github.com/BananaScripts/Meteorological-Data-Collector-Database/wiki/Como-rodar-O-banco)

Commits: 
[02f5dad](https://github.com/BananaScripts/Meteorological-Data-Collector-Database/commit/02f5dad75585dc74468cede9a71e589626393e55)
[abdee3c](https://github.com/BananaScripts/Meteorological-Data-Collector-Database/commit/abdee3c5000eb43a8f4d6ab8973e92568e3e2543)
