### ISSUE TITLE
Implementar as estações meterológicas funcionando no sistema.

### ISSUE THREAD

**Issue by BananaaScript** [BananaScripts/Meteorological-Data-Collector#27]
Configurar a conexão entre cada estação meteorológica e o sistema
    - Estabelecer protocolos de comunicação (ex: MQTT, HTTP)
    - Configurar firewall e portas necessárias
Implementar sistema de monitoramento de status das estações
    - Criar painel de controle para visualização do status de cada estação
    - Implementar alertas para falhas de conexão
    - Desenvolver sistema de log detalhado para cada estação

Requito: 2

**Comment by DouglasMedeiros1** [comment]
9288f24f07927b39c6a79539add97775c15e76b0

**Comment by DouglasMedeiros1** [comment]
Merge:

https://github.com/BananaScripts/Meteorological-Data-Collector-Backend/pull/26
