### ISSUE TITLE
O sistema deve identificar estações pelo UUID único ao receber dados e validar a integridade das informações.

### ISSUE THREAD

**Issue by BananaaScript** [BananaScripts/Meteorological-Data-Collector#29]
Implementar sistema de verificação de UUID
    - Desenvolver mecanismo de autenticação baseado em UUID

Desenvolver sistema de validação de integridade de dados
     - Implementar verificação da integridade dos dadso

Requisito: 2

**Comment by DouglasMedeiros1** [comment]
Commits

https://github.com/BananaScripts/Meteorological-Data-Collector-Backend/commit/41cd82307ccfd745a3834c82e67d3682f870915c

https://github.com/BananaScripts/Meteorological-Data-Collector-Backend/commit/2e89cb9896ff14001deb01bfc4ec34971f89e3d8

https://github.com/BananaScripts/Meteorological-Data-Collector-Backend/commit/e98a3362051f83dfda36ffba19fc49b628d16b60
