### ISSUE TITLE
Terminar sistema de processamento de dados, acrescentando o tratamento dos dados das estações.

### ISSUE THREAD

**Issue by BananaaScript** [BananaScripts/Meteorological-Data-Collector#30]
Criar sistema de filtragem de dados
    - Retirar dados desnecessários para o sistema montado (Ex. Se uma estação mandar latitude e longitude, retirar esses valores)
    - Criar sistema de preenchimento de dados faltantes
Desenvolver sistema de normalização de dados
    - Implementar conversão automática de unidades
    - Criar mecanismos de ajuste para diferentes tipos de sensores
    - Desenvolver sistema de correção de erros sistemáticos

Requsito: 1

**Comment by DouglasMedeiros1** [comment]
Commit
3f81c153e6b873f07fbb5ee4b03c73dc5add2f58
