### ISSUE TITLE
Redefinir base de dados do sistema

### ISSUE THREAD

**Issue by BananaaScript** [BananaScripts/Meteorological-Data-Collector#36]
### Reestrurar quantidade minima de dados, relacionando os dados simulados e os dados base do Supabase.

Para isso é necessário:

- Deletar todos os dados já cadastrados em ambos os bancos
- Definir com o responsavel dos testes (Antonio) a quantia de dados minimos para testes
- Cadastrar dados de base no banco relacional, para que ele filtre no tratamento os dados do banco não relacional
- Validar com o  Orientador de Devops (Sakaue) sobre a qualidade dos dados

Requisito: 10

**Comment by DouglasMedeiros1** [comment]
Commit do Backend:

[fc06e9ce3f5ac2ce0e2d8c57d0960961e955f5af](https://github.com/BananaScripts/Meteorological-Data-Collector-Backend/commit/fc06e9ce3f5ac2ce0e2d8c57d0960961e955f5af)

Commit do BD

[196a044e4860b48f7689a2269371141678d3aed1](https://github.com/BananaScripts/Meteorological-Data-Collector-Database/commit/196a044e4860b48f7689a2269371141678d3aed1)
