### ISSUE TITLE
Telas de Educação

### ISSUE THREAD

**Issue by miguelcondesantos** [BananaScripts/Meteorological-Data-Collector#56]
Criar telas que mostrem explicações visuais sobre o significado e importância de cada parâmetro meteorológico, ajudando o usuário a interpretar os dados.

Requisito: 8

**Comment by BrunoFerCam** [comment]
Closes #56
Commit: https://github.com/BananaScripts/Meteorological-Data-Collector-Frontend/commit/c1078313c3dda2bf8b86a93ed252dca842265039
