### ISSUE TITLE
CRUD de Usuários

### ISSUE THREAD

**Issue by BananaaScript** [BananaScripts/Meteorological-Data-Collector#8]
CRUD de Usuários

- Create (Criar Usuário):
O administrador pode cadastrar novos usuários, fornecendo:
Nome
Senha
Nível de acesso (administrador ou usuário comum)

- Read (Visualizar Usuários):
O administrador pode ver uma lista de todos os usuários cadastrados, com:
Nome
Nível de acesso
Ele pode filtrar usuários por nome ou nível de acesso.

- Update (Atualizar Usuário):
O administrador pode editar as informações de um usuário, como:
Nome
Senha
Nível de acesso

- Delete (Excluir Usuário):
O administrador pode remover um usuário do sistema.
Uma confirmação é solicitada antes de excluir o usuário permanentemente.

**Comment by GaSiqueira** [comment]
24fb29c
