### ISSUE TITLE
Criação das Telas do Adimistrador

### ISSUE THREAD

**Issue by BananaaScript** [BananaScripts/Meteorological-Data-Collector#9]
Desenvolver uma interface navegável incial para que o adimistrador possa fazer o:

- Gerenciamento de Estações:
Cadastrar, editar, visualizar e excluir estações meteorológicas

- Gerenciamento de Parâmetros:
Definir, editar, visualizar e excluir parâmetros monitorados pelas estações

- Gerenciamento de Alertas:
Configurar alertas, editar limites e visualizar as notificações

- Gerenciamento de Usuários:
Cadastrar, visualizar, editar e excluir usuários.

**Comment by DouglasMedeiros1** [comment]
Adicionei o Read do Crud e integrei o front com backend

COMMIT: 
216d98f

**Comment by DouglasMedeiros1** [comment]
Terminei o Crud das estações

Commit: [b8b55c2](https://github.com/BananaScripts/Meteorological-Data-Collector-Frontend/commit/b8b55c204956efb7f5154058c71133282307406c)

**Comment by DouglasMedeiros1** [comment]
Terminei o crud de Parametros, usuarios e alarmes no frontend

COMMIT: 
050c2899ae94aab274e8c191793fd351e6c89bbc

**Comment by DouglasMedeiros1** [comment]
Alterei o backend para poder terminar a integração do sistema como um todo

COMMIT:
ce20a73c273e23ce18b5805f455d9c194c1c929d
